import Head from 'next/head' 
import styles from '../styles/Home.module.css'
import Nav from '../components/Layout/nav'
import Main from '../components/main'
export const getStaticProps = async ()=>{
  debugger;
  const response = await fetch(`https://dummyjson.com/users/?skip=90&limit=20`)
  const data = await response.json(); 
  return { props: { data } }
}
export default function Home({data}) {
  return (
    <div>
      <Head>
        <title>Clone | Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
          <Nav/>
          <Main data= {data}/>
      </div>
    </div>
  )
}
